# Site settings
title: "Redoblue's Blog"
header-img: "img/home-bg.jpg"
email: "redoblue@hotmail.com"
description: ""
baseurl: ""
url: "http://redoblue.github.io"
github_username: "Redoblue"

# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 10
timezone: "Asia/Beijing"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
plugins_dir: ["jekyll-paginate", "jekyll-sitemap"]
gems: ["jekyll-paginate"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
